# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "inference.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0finference.proto\x12\tinference"$\n\x10InferenceRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02"6\n\x0eInferenceReply\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t"2\n\x0e\x45mbeddingReply\x12\x11\n\tembedding\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x32\xad\x01\n\x0eModelInference\x12M\n\x11PredictConfidence\x12\x1b.inference.InferenceRequest\x1a\x19.inference.InferenceReply"\x00\x12L\n\x10PredictEmbedding\x12\x1b.inference.EmbeddingRequest\x1a\x19.inference.EmbeddingReply"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "inference_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_INFERENCEREQUEST"]._serialized_start = 30
    _globals["_INFERENCEREQUEST"]._serialized_end = 66
    _globals["_INFERENCEREPLY"]._serialized_start = 68
    _globals["_INFERENCEREPLY"]._serialized_end = 122
    _globals["_EMBEDDINGREQUEST"]._serialized_start = 124
    _globals["_EMBEDDINGREQUEST"]._serialized_end = 156
    _globals["_EMBEDDINGREPLY"]._serialized_start = 158
    _globals["_EMBEDDINGREPLY"]._serialized_end = 208
    _globals["_MODELINFERENCE"]._serialized_start = 211
    _globals["_MODELINFERENCE"]._serialized_end = 384
# @@protoc_insertion_point(module_scope)
